name: Your New Jekyll Site
markdown: redcarpet
highlighter: pygments
exclude:
  - Gemfile
  - Gemfile.lock

assets:
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets

port: 8000